version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=${DB_PORT}
    command: [ "postgres", "-p", "${DB_PORT}" ]
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: nest-docker
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db